import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: 20,
  },
  inputContainer: {
    width: '100%',
    marginTop: 20,
    flexDirection: 'column',
    flex: 1,
  },
  textInput: {
    width: '100%',
    height: 60,
    fontSize: 20,
    borderColor: '#333',
    borderRadius: 8,
    backgroundColor: '#f0f0f0',
    marginTop: 8,
    padding: 8,
  },
  inputLabel: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  goButton: {
    width: '100%',
    height: 60,
    fontSize: 20,
    borderColor: '#333',
    borderRadius: 8,
    backgroundColor: '#40e0d0',
    marginTop: 20,
    padding: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  goButtonText: {
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
    color: '#fff',
  },
  logoContainer: {
    width: '100%',
    flex: 1,
    flexDirection: 'column-reverse',
    alignItems: 'center',
  },
  logoAnimation: {},
  logoText: {
    fontSize: 40,
    fontWeight: 'bold',
    color: '#333',
  },
  fieldContainer: {
    width: '100%',
    marginBottom: 200,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: 20,
  },
  registerButton: {
    width: '100%',
    height: 60,
    fontSize: 20,
    borderColor: '#333',
    borderRadius: 8,
    backgroundColor: '#4287f5',
    marginTop: 20,
    padding: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  registerButtonText: {
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
    color: '#fff',
  },
});
